#!/usr/bin/env bash

# Copyright 2023 Calum Murray
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Synching upstream remote with origin"
GIT_STASH_MESSAGE="${RANDOM}"
git stash push -m "{GIT_STASH_MESSAGE}"
git checkout main
git pull upstream main --ff-only
git push origin main
git switch -
git stash list | grep "${GIT_STASH_MESSAGE}" && git stash pop 0 --index
exit 0
